### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by WebFreak001** [KanzakiKino/w4d#1]
ctrl-c/ctrl-v

**Comment by KanzakiKino** [comment]
glfwSetClipboardString doesn't work properly on my Arch. So I'm going to fix the issue or find the another way to operate the clipboard.

**Comment by WebFreak001** [comment]
are you sure it doesn't work? works on my arch install

**Comment by KanzakiKino** [comment]
Yes, glfwSetClipboardString had no effects.
There might be issue in ClipboardManager. So I'm trying to fix.

**Comment by WebFreak001** [comment]
on linux, after you close a window if there was clipboard copied from that window, the clipboard will go away except if you use a clipboard manager. Have you tried keeping the window open?

**Comment by KanzakiKino** [comment]
Oh, I didn't know. It worked properly.
