### ISSUE TITLE
ScrollPanelWidget not working properly

### ISSUE THREAD

**Issue by WebFreak001** [KanzakiKino/w4d#8]
I have this layout:
```
VerticalScrollPanelWidget
.contents:
  PanelWidget:VerticalLineupLayout
    PanelWidget:VerticalMonospacesSplitLayout {x10}
      PanelWidget:HorizontalLineupLayout
        TextWidget
        TextWidget
      TextWidget
      TextWidget
```

the scrollbar doesn't go all the way down if the parent container is not big enough (children are clipped outside). After manually setting the `{x10}` PanelWidget height to 80px it works for more sizes, but it's still broken.

Am I using the ScrollPanelWidget wrong?

**Comment by KanzakiKino** [comment]
This might help you:

In the Widgets that use layout not support children,
style.box.size.width = Scalar.Auto // Uses wantedSize.
style.box.size.height = Scalar.None // Fills the parent.

(TextWidget's wantedSize is size of the text, any other Widgets' is (0,0).)
(If Scalar.Auto is specified and wantedSize is 0, fills the parent.)


In the Widgets that are use layout support children:

style.box.size.width = Scalar.Auto // Uses wantedSize.
style.box.size.height = Scalar.None // Shrink as small as.possible.

(PanelWidget's wantedSize is usually (0,0). So you can expand as big as possible if specify Scalar.Auto.)

The parent means given size.

**Comment by KanzakiKino** [comment]
```d
auto scroll = new VerticalScrollPanelWidget;
scroll.style.box.size.width  = 100.pixel;
scroll.style.box.size.height = 100.pixel;
addChild( scroll );

auto panel1 = new PanelWidget;
panel1.setLayout!VerticalLineupLayout;
scroll.contents.addChild( panel1 );

foreach ( i; 0..10 ) {
    auto panel2 = new PanelWidget;
    panel2.setLayout!VerticalMonospacedSplitLayout;
    panel1.addChild( panel2 );

    auto panel3 = new PanelWidget;
    panel3.setLayout!HorizontalLineupLayout;
    panel3.style.box.size.height = Scalar.Auto;
    panel2.addChild( panel3 );

    auto text1 = new TextWidget;
    text1.loadText( "hogehogehoge", fontface );
    panel3.addChild( text1 );

    auto text2 = new TextWidget;
    text2.loadText( "fugafugafuga", fontface );
    panel3.addChild( text2 );

    auto text3 = new TextWidget;
    text3.loadText( "piyopiyopiyo", fontface );
    text3.style.box.size.height = Scalar.None;
    panel2.addChild( text3 );

    auto text4 = new TextWidget;
    text4.loadText( "fuyofuyofuyo", fontface );
    text4.style.box.size.height = Scalar.None;
    panel2.addChild( text4 );
}
```
It worked for me without problem.

**Comment by KanzakiKino** [comment]
And what version are you using? My code worked at e962ca7a07adfb3f8285c1878033ae8272500a1a.

**Comment by WebFreak001** [comment]
I have the full code on https://gitlab.com/WebFreak001/TTRLauncherLite but when I come home today I will try to make a reproducible test case

**Comment by KanzakiKino** [comment]
https://gitlab.com/WebFreak001/TTRLauncherLite/blob/master/source/widget/root.d#L54
Please replace with VerticalSplitLayout.

LineupLayout gives children a client size of the owner whenever.
But SplitLayout gives them the remained size.

If A's height is 50%, and B's height is 100%:
- By VerticalLineupLayout, sum height of all children will be 150%.
- By VerticalSplitLayout, it will be 100%.

**Comment by WebFreak001** [comment]
oh yep that fixed it thanks.

Maybe you could add some ddoc to the layouts so it's clear what they all do
